package miden:storage-example@1.0.0;

use miden:base/core-types@1.0.0;

interface foo {
    use core-types.{felt, word, core-asset};

    set-asset-qty: func(pub-key: word, asset: core-asset, qty: felt);
    get-asset-qty: func(asset: core-asset) -> felt;
}

world foo-world {
    include miden:core-import/all@1.0.0;

    export foo;
}
